### ISSUE TITLE
oscapd runs at 100% cpu time and call's to it will fail

### ISSUE THREAD

**Issue by tuxmaster** [OpenSCAP/openscap-daemon#142]
Version: 0.1.10
OS: CentOS 7.5

1.  call oscapd-cli task
2. call oscapd-cli task 1 disable
The second command will fail with:

> Traceback (most recent call last):
>   File "/usr/bin/oscapd-cli", line 849, in <module>
>     main()
>   File "/usr/bin/oscapd-cli", line 835, in main
>     cli_task(dbus_iface, task_accessor, args)
>   File "/usr/bin/oscapd-cli", line 273, in cli_task
>     dbus_iface.SetTaskEnabled(args.task_id, False)
>   File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
>     **keywords)
>   File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
>     message, timeout)
> dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

And now all "oscapd-cli" calls will with the same error.

Running oscapd in verbose mode will not shown any output.

**Comment by cipherboy** [comment]
(edited for formatting)

@tuxmaster For future reference, use three backticks (`) to start and end a "block code mode" and single backticks around commands to give them an inline-code mode. :)

(if you click edit on your post you should be able to see my changes)
