### ISSUE TITLE
oscapd should be able to start even without Atomic is installed

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/openscap-daemon#35]
Reproducer:
 * try to install oscapd
 * remove docker&atomic.
 * Play. :)

**Comment by isimluk** [comment]
More details:
```
Nov 27 13:00:58 dhcp-2-150.brq.redhat.com oscapd[24365]: Traceback (most recent call last):
Nov 27 13:00:58 dhcp-2-150.brq.redhat.com oscapd[24365]: File "/usr/bin/oscapd", line 22, in <module>
Nov 27 13:00:58 dhcp-2-150.brq.redhat.com oscapd[24365]: from openscap_daemon import dbus_daemon
Nov 27 13:00:58 dhcp-2-150.brq.redhat.com oscapd[24365]: File "/usr/lib/python2.7/site-packages/openscap_daemon/dbus_daemon.py", line 23, in <module>
Nov 27 13:00:58 dhcp-2-150.brq.redhat.com oscapd[24365]: from openscap_daemon.cve_scanner.cve_scanner import Worker
Nov 27 13:00:58 dhcp-2-150.brq.redhat.com oscapd[24365]: File "/usr/lib/python2.7/site-packages/openscap_daemon/cve_scanner/cve_scanner.py", line 19, in <module>
Nov 27 13:00:58 dhcp-2-150.brq.redhat.com oscapd[24365]: from openscap_daemon.cve_scanner.applicationconfiguration \
Nov 27 13:00:58 dhcp-2-150.brq.redhat.com oscapd[24365]: File "/usr/lib/python2.7/site-packages/openscap_daemon/cve_scanner/applicationconfiguration.py", line 24, in <module>
Nov 27 13:00:58 dhcp-2-150.brq.redhat.com oscapd[24365]: import docker
Nov 27 13:00:58 dhcp-2-150.brq.redhat.com oscapd[24365]: ImportError: No module named docker
Nov 27 13:00:58 dhcp-2-150.brq.redhat.com systemd[1]: oscapd.service: main process exited, code=exited, status=1/FAILURE
Nov 27 13:00:58 dhcp-2-150.brq.redhat.com systemd[1]: Failed to start OpenSCAP Daemon.
```

**Comment by mpreisler** [comment]
Basic support for this since 1fbe86becacae31079b0d10a301a91ac1657369a

`oscapd` starts and errors are only triggered when user attempts to perform container related tasks.
