### ISSUE TITLE
Daemon fails to start due to missing Python requests module

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap-daemon#47]
I have run into issue that I wasn't able to start OpenSCAP Daemon using `systemctl start oscapd` on Fedora 22 Cloud. It seems to be dependent on Python's "requests" module. Here is a snippet from my journal:
```
Jan 21 08:32:02 nec-em18.rhts.eng.bos.redhat.com systemd[1]: Starting OpenSCAP Daemon...
Jan 21 08:32:02 nec-em18.rhts.eng.bos.redhat.com oscapd[10409]: Traceback (most recent call last):
Jan 21 08:32:02 nec-em18.rhts.eng.bos.redhat.com oscapd[10409]: File "/usr/bin/oscapd", line 22, in <module>
Jan 21 08:32:02 nec-em18.rhts.eng.bos.redhat.com oscapd[10409]: from openscap_daemon import dbus_daemon
Jan 21 08:32:02 nec-em18.rhts.eng.bos.redhat.com oscapd[10409]: File "/usr/lib/python2.7/site-packages/openscap_daemon/dbus_daemon.py", line 23, in <module>
Jan 21 08:32:02 nec-em18.rhts.eng.bos.redhat.com oscapd[10409]: from openscap_daemon.cve_scanner.cve_scanner import Worker
Jan 21 08:32:02 nec-em18.rhts.eng.bos.redhat.com oscapd[10409]: File "/usr/lib/python2.7/site-packages/openscap_daemon/cve_scanner/cve_scanner.py", line 23, in <module>
Jan 21 08:32:02 nec-em18.rhts.eng.bos.redhat.com oscapd[10409]: from openscap_daemon.cve_scanner.generate_summary import Create_Summary
Jan 21 08:32:02 nec-em18.rhts.eng.bos.redhat.com oscapd[10409]: File "/usr/lib/python2.7/site-packages/openscap_daemon/cve_scanner/generate_summary.py", line 27, in <module>
Jan 21 08:32:02 nec-em18.rhts.eng.bos.redhat.com oscapd[10409]: from openscap_daemon.cve_scanner.image_scanner_client import Client
Jan 21 08:32:02 nec-em18.rhts.eng.bos.redhat.com oscapd[10409]: File "/usr/lib/python2.7/site-packages/openscap_daemon/cve_scanner/image_scanner_client.py", line 37, in <module>
Jan 21 08:32:02 nec-em18.rhts.eng.bos.redhat.com oscapd[10409]: import requests
Jan 21 08:32:02 nec-em18.rhts.eng.bos.redhat.com oscapd[10409]: ImportError: No module named requests
Jan 21 08:32:03 nec-em18.rhts.eng.bos.redhat.com systemd[1]: oscapd.service: main process exited, code=exited, status=1/FAILURE
Jan 21 08:32:03 nec-em18.rhts.eng.bos.redhat.com systemd[1]: Failed to start OpenSCAP Daemon.
```
I use openscap-daemon-0.1.1-3.fc22.noarch.

As from I understand, the daemon itself should not depend on `requests`, only the client part should depend on it.

**Comment by mpreisler** [comment]
Fixed in 1a0d99b9e1d4da6542878f78e0242915c80c023b
