### ISSUE TITLE
oscapd-cli can't parse its arguments on Fedora23

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap-daemon#50]
Hello!
I have openscap-daemon-0.1.1-4.fc23.noarch on Fedora 23. I can't run the `oscapd-cli` command. I get:
```
[root@localhost ~]# oscapd-cli
Traceback (most recent call last):
  File "/usr/bin/oscapd-cli", line 752, in <module>
    main()
  File "/usr/bin/oscapd-cli", line 698, in main
    if args.version:
AttributeError: 'Namespace' object has no attribute 'version'
```
I think it is wrong processing of object returned by `parse_args()` from argparse. Perhaps it is because Python 3 is used as interpreter.

**Comment by mpreisler** [comment]
Fixed in 596a7054b7035d068f40e230d106b5286c0cc1c1

```
$ python2 ./oscapd-cli --version
oscapd-cli 0.1.1
$ python3 ./oscapd-cli --version
oscapd-cli 0.1.1

```
