### ISSUE TITLE
oscapd-cli run without any arguments gives a traceback on Python 3

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap-daemon#51]
Hello! I run `oscapd-cli` on Fedora23 without any argument.
```
[root@localhost ~]# oscapd-cli
Traceback (most recent call last):
  File "/usr/bin/oscapd-cli", line 750, in <module>
    main()
  File "/usr/bin/oscapd-cli", line 731, in main
    if args.action == "status":
AttributeError: 'Namespace' object has no attribute 'action'
```
I think it would give me some error message or usage or help, but no traceback.

**Comment by mpreisler** [comment]
The output is very slightly different but now it works in both. Fixed in 1302d225b6cec023397a1bad38c8e5897fb83dd6

```
$ python2 ./oscapd-cli
usage: oscapd-cli [-h] [-v] {eval,task,task-create,status,result} ...
oscapd-cli: error: too few arguments
$ echo $?
2

$ python3 ./oscapd-cli
usage: oscapd-cli [-h] [-v] {eval,task,task-create,status,result,scan} ...
oscapd-cli: error: the following arguments are required: action
$ echo $?
2
```

Thanks a lot for your tickets, please keep them coming :-)
